name: Criar diretório e arquivo no Ubuntu

on:
  push:
    branches:
      - feature/criar-arquivo  # A pipeline será disparada quando houver push na branch 'feature/criar-arquivo'

jobs:
  deploy:
    runs-on: ubuntu-latest  # A execução do job ocorrerá em uma máquina Ubuntu

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v2  # Baixa o código do repositório

      - name: Configurar chave SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Usando a chave privada configurada no GitHub Secrets

      - name: Criar diretório no servidor
        run: |
          set -e  # Faz com que o script pare imediatamente em caso de erro
          echo "Iniciando conexão SSH..."
          
          # Tentando criar o diretório no servidor
          ssh -o StrictHostKeyChecking=no jaime@servidores-linux.70-71-bc-12-b3-87@cloud.shellhub.io "mkdir -p /home/jaime/novo_diretorio"
          
          echo "Diretório criado com sucesso!"

      - name: Criar arquivo dentro do diretório no servidor
        run: |
          set -e  # Faz com que o script pare imediatamente em caso de erro
          echo "Criando o arquivo dentro do diretório..."
          
          # Criando um arquivo dentro do diretório
          ssh -o StrictHostKeyChecking=no jaime@servidores-linux.70-71-bc-12-b3-87@cloud.shellhub.io "echo 'Conteúdo do arquivo criado pela pipeline' > /home/jaime/novo_diretorio/novo_arquivo.txt"
          
          echo "Arquivo criado com sucesso dentro do diretório!"
