name: Executar Terraform para Criar Diretório e Arquivo no Ubuntu

on:
  push:
    branches:
      - feature/criar-diretorio-terraform

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v2

      - name: Configurar chave SSH
        uses: actions/setup-ssh@v4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'

      - name: Validar Terraform
        run: |
          set -e
          terraform validate

      - name: Inicializar Terraform
        run: |
          terraform init

      - name: Executar Terraform Plan
        run: |
          terraform plan
          
      - name: Aplicar Terraform
        run: |
          set -e
          terraform apply -auto-approve

      - name: Finalizar com sucesso
        if: success()
        run: echo "Terraform executado com sucesso. Diretório e arquivo criados."

      - name: Exibir mensagem de erro se houver falha
        if: failure()
        run: |
          echo "### ERRO NA EXECUÇÃO DO TERRAFORM ###"
          echo "Houve um erro durante a execução do Terraform. Verifique os logs acima para mais detalhes."