name: Executar Terraform para Criar Diretório e Arquivo no Ubuntu

on:
  push:
    branches:
      - feature/criar-diretorio-terraform  # A pipeline será disparada quando houver push na branch 'feature/criar-diretorio-terraform'

jobs:
  terraform:
    runs-on: ubuntu-latest  # A execução do job ocorrerá em uma máquina Ubuntu

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v2  # Baixa o código do repositório

      - name: Configurar chave SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Usando a chave privada configurada no GitHub Secrets

      - name: Instalar Terraform
        run: |
          # Atualizando a lista de pacotes
          sudo apt-get update
          
          # Instalando dependências necessárias, incluindo curl e libcurl4
          sudo apt-get install -y gnupg software-properties-common curl libcurl4

          # Atualizando curl e libcurl4 para a versão mais recente
          sudo apt-get upgrade -y curl libcurl4

          # Adicionando o repositório oficial do HashiCorp
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          sudo apt-get update  # Atualizando novamente a lista de pacotes com o repositório do HashiCorp

          # Instalando o Terraform
          sudo apt-get install -y terraform  # Instalando o Terraform

      - name: Validar Terraform
        run: |
          set -e  # Faz com que o script pare imediatamente em caso de erro
          terraform validate  # Valida os arquivos do Terraform

      - name: Inicializar Terraform
        run: |
          terraform init  # Inicializa o Terraform

      - name: Executar Terraform Plan
        run: |
          terraform plan  # Exibe o plano de execução para o Terraform
          
      - name: Aplicar Terraform
        env:
          TF_VAR_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}  # Passando a chave SSH como variável para o Terraform
        run: |
          set -e  # Faz com que o script pare imediatamente em caso de erro
          terraform apply -auto-approve  # Aplica as mudanças definidas no Terraform

      - name: Finalizar com sucesso
        if: success()  # Esta etapa só executa se todos os passos anteriores tiverem sido bem-sucedidos
        run: echo "Terraform executado com sucesso. Diretório e arquivo criados."

      - name: Exibir mensagem de erro se houver falha
        if: failure()  # Esta etapa só executa se algum passo anterior falhar
        run: |
          echo "### ERRO NA EXECUÇÃO DO TERRAFORM ###"
          echo "Houve um erro durante a execução do Terraform. Verifique os logs acima para mais detalhes."
